### PR TITLE
3.0.0 is out so don't special case things as being deferred

### PR DESCRIPTION
**Pull request by iamamoose**

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by t8m** [comment]
Mark, please rebase this against freshly pulled master branch.

**Comment by levitte** [comment]
Ping?

**Comment by levitte** [comment]
Er, this got merged to github.com, which is just a mirror.
Furthermore, the rebase that @t8m suggested is necessary, as we don't accept merge commits...

**Comment by levitte** [comment]
Recreated, see #127

**Pull request merged**
