### PR TITLE
cherry-checker: add a 'fixes' column

### PR DESCRIPTION
**Pull request by mspncp**
Scans the commit messages for 'Fixes' annotations and displays them in an additional column.

Example output:

```
$ cherry-checker  --all --remote

These cherries are hanging on the git-tree:

  <-  origin/master
  ->  origin/OpenSSL_1_1_1-stable
  ==  both

 prnum | fixes | br |   commit   |   subject
 ----- | ----- | -- | ---------- | -------------------------------------------
 #7467 |       | == | 28361a0b82 | RAND: ensure INT32_MAX is defined 
 #7467 |       | == | f81b043ad8 | RAND: ensure INT32_MAX is defined 
 #7352 |       | <- | 97b0b713fb | RSA security bits calculation 
 #7455 | #7449 | == | ece482ff3a | RAND_add(): fix heap corruption in error path 
 #7455 | #7449 | == | 5b4cb385c1 | RAND_add(): fix heap corruption in error path 
 #7451 |       | -> | 132fd512ad | build file templates: have targets for all shared library names 
 #7451 |       | <- | d8cac50b02 | build file templates: have targets for all shared library names 
 #7434 | #7433 | == | 8c6371f9f7 | Don't complain and fail about unknown TLSv1.3 PSK identities in s_serv... 
 #7434 | #7433 | == | 2d015189b9 | Don't complain and fail about unknown TLSv1.3 PSK identities in s_serv... 
 #7375 | #6934 | == | d1bfd8076e | Buffer a ClientHello with a cookie received via DTLSv1_listen 
 #7375 |       | == | 585e691948 | Use the read and write buffers in DTLSv1_listen() 
 #7375 | #6934 | == | 079ef6bd53 | Buffer a ClientHello with a cookie received via DTLSv1_listen 
 #7375 |       | == | 2fc4c77c3f | Use the read and write buffers in DTLSv1_listen() 
 #7431 |       | == | 6c529877cd | Test DTLS cookie generation and verification 
 #7431 | #7428 | == | a6a83827a0 | Fix a DTLS memory leak 
 #7431 |       | == | edcd29efd3 | Test DTLS cookie generation and verification 
 #7431 | #7428 | == | 01666a8c1d | Fix a DTLS memory leak 
 #7294 |       | <- | 9986bfefa4 | sha/asm/keccak1600-armv8.pl: halve the size of hw-assisted subroutine. 
 #7400 |       | == | a66c361a77 | Configurations/15-android.conf: add support for "standalone toolchain"... 
 #7400 |       | == | 03ad7c009e | Configurations/15-android.conf: add support for "standalone toolchain"... 
 #7420 |       | == | fc762e7d5c | arch/async_posix.h: improve portability. 
 #7420 |       | == | 9d71a24ebf | arch/async_posix.h: improve portability. 
 ...
```

### CODE REVIEW

**Comment by richsalz** [comment]
This is a nice script, good work!

**Comment by mspncp** [comment]
ping @openssl/omc 

(I know python is not your métier, but you can trust me, it works ;-)

**Comment by levitte** [comment]
Merged in e759eccf4e6bd38f8a16e8ee053b1da978d4fb89

**Comment by mspncp** [comment]
Thanks!

**Pull request closed without merging**
