### PR TITLE
Update release script to include adding new releases to the provider compatibility checks

### PR DESCRIPTION
**Pull request by paulidale**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Approved assuming openssl/openssl#19218 is merged

**Comment by t8m** [comment]
This needs a rebase

**Comment by nhorman** [comment]
@paulidale Can you please rebase this?

**Comment by t8m** [comment]
This also needs some adjustments - the update is needed only in case there is a new minor release (not for patch releases).

**Comment by paulidale** [comment]
I've rebased and updated the text.

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged. Thank you.

**Pull request closed without merging**
