### PR TITLE
Ensure sanitizer builds use no-asm

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Comment by DDvO** [comment]
This should of course be accompanied by a PR removing `no-asm` from the CI sanitizer runs on master.

**Review by levitte — APPROVED** [review]

**Comment by DDvO** [comment]
@mattcaswell, wanna merge this?

Is there meanwhile a PR that takes `no-asm` out of all sanitizer builds on openssl/openssl:master?

**Comment by mattcaswell** [comment]
Pushed.

**Comment by mattcaswell** [comment]
> Is there meanwhile a PR that takes no-asm out of all sanitizer builds on openssl/openssl:master?

Not yet...

**Comment by mattcaswell** [comment]
> Not yet...

There is now:

https://github.com/openssl/openssl/pull/13607

**Pull request closed without merging**
