### PR TITLE
ghmerge: Fix branch handling

### PR DESCRIPTION
**Pull request by DDvO**
* Correct saving and restoring original branch state
* Properly catch the error that `copy-of-...` already exists
* Improve robustness and clarity regarding which ref branch is used
* Avoid checking out ref branch if not needed

### CODE REVIEW

**Comment by DDvO** [comment]
BTW, these improvements came up when I faced the situation that many PRs need to be merged to both the `master` and `openssl-3.0` branches.
I meanwhile use `ghmerge` typically via the following aliases:
```
alias ghm='ghmerge --nobuild --ref master'
alias ghm3='ghmerge --nobuild --ref openssl-3.0 --cherry-pick'
alias ghm1='ghmerge --nobuild --ref OpenSSL_1_1_1-stable --cherry-pick'
```
e.g., as follows:
```
ghm 16747 @t8m 
ghm3 16747 @t8m 
```
With the improvements proposed here, this can be done from any directory having `openssl-git@git.openssl.org:openssl.git` as `upstream` remote.

**Comment by paulidale** [comment]
We have a `pick-to-branch` script for cherry picking single commits.  Might it be worth improving that too?

`pick-to-brach <commit> 3.0`

**Comment by DDvO** [comment]
Can someone with sufficient privileges please merge this?

BTW, is there (still) a good reason for not allowing this to committers?

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged, thank you.

**Pull request closed without merging**
