### PR TITLE
run-checker: remove the fuzzing builds

### PR DESCRIPTION
**Pull request by paulidale**
Not to be merged until after openssl/openssl#16438 is merged and working.

### CODE REVIEW

**Comment by paulidale** [comment]
Ping for review openssl/openssl#16438 merges soon...

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
This means that we can drop the run-checker VM as well, right?

**Comment by paulidale** [comment]
Yes, but separate PR

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Would it actually make sense to remove the run-checker directory completely?

**Comment by paulidale** [comment]
Yes we should remove it, in a different PR.

**Comment by t8m** [comment]
Merged. Thank you.

**Pull request closed without merging**
