### PR TITLE
rand-drbg: Add conversion script to create data for DRBG testing.

### PR DESCRIPTION
**Pull request by paulidale**
NIST's DRBG test data set isn't ideal for evp_test to process.  This script massages the data into a format which is more suitable.

### CODE REVIEW

**Comment by paulidale** [comment]
OMC review required (I think).

**Comment by richsalz** [comment]
FWIW, I don't think we need to include the ZIP file (and since it's so big, shouldn't).
Ideally, the conversion script is rewritten in perl.

**Comment by paulidale** [comment]
I don't mind dropping the zip file.  I included it because it represents the data at the point in time they were snapshot.

**Comment by paulidale** [comment]
Ping @openssl/omc

**Comment by paulidale** [comment]
Ping @openssl/omc

**Comment by mattcaswell** [comment]
> OMC review required (I think).

Actually OTC approval is needed for the tools repo.

**Comment by paulidale** [comment]
Ping @openssl/otc

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
