### PR TITLE
tls1_3 is now on by default so we should instead test no-tls1_3

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Comment by richsalz** [comment]
ping @mattcaswell and @levitte

**Comment by mattcaswell** [comment]
Pushed. Thanks for the reminder.

**Comment by richsalz** [comment]
Does @levitte just run the script out of the repo, or does he have to edit something else?  Hence the ping to him.

**Comment by levitte** [comment]
I need to perform a `git pull --rebase`, 's all.

**Comment by levitte** [comment]
Done

**Pull request closed without merging**
