### PR TITLE
Add run-perf.sh

### PR DESCRIPTION
**Pull request by vdukhovni**
This is just the run-perf.sh script for sharing with the team, work-in-progress, do not merge.

### CODE REVIEW

**Comment by Sashan** [comment]
I think this is good enough. I gave it try. to speed things up I've modified some parameters:
  - reduced number of iterations to two
  - reduced number of threads to 4 and 8
  - reduced versions to 1.1.1, 3.0, 3.3 and master
 
works flawlessly. I think it's good enough. I would not waste too much time with it. What we really need to decide are parmeters which we will be using for testing on all platforms:
  - number of iterations: the first version from @nhorman  got 50, I've reduced the number to 25, but it still feels too much
  - versions I think @mattcaswell proposal to test 1.1.1, 3.0, 3.3 and master is sufficient
  - number of threads I like what @nhorman suggested: 1 2 4 8 16 32 64 128

with parameters like above we can expect test duration on ryzen 7 with 8 cores roughly 12 hours.

**Review by t8m — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Review by Sashan — APPROVED** [review]
it's good enough to go in.

**Comment by vdukhovni** [comment]
Applied a bit more polish and trimmed the version list. Left iterations and threads alone for now, pending future decisions. Should be good to merge.

**Comment by nhorman** [comment]
merged

**Pull request closed without merging**
